### ISSUE TITLE
make the wire-frames mock-ups

### ISSUE THREAD

**Issue by crizy182** [wise-crab/healthcare_Frontend#4]
https://balsamiq.cloud/shikon8/p64hqz4 -> Pacientes
https://balsamiq.cloud/shikon8/pvvje4g   -> Bacteriologo
https://balsamiq.cloud/shikon8/poix2by -> Medico
https://balsamiq.cloud/shikon8/pbzickn -> Administrador

**Comment by jeff-js** [comment]
Ya se aprobaron los mokups

https://balsamiq.cloud/shikon8/p64hqz4 -> Pacientes
https://balsamiq.cloud/shikon8/pvvje4g -> Bacteriologo
https://balsamiq.cloud/shikon8/poix2by -> Medico
https://balsamiq.cloud/shikon8/pbzickn -> Administrador
